# Generated by Django 5.1.5 on 2025-03-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_member_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_start_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ شروع عضویت'),
        ),
    ]
