# Generated by Django 5.1.5 on 2025-04-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_member_membership_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='phone_number',
        ),
    ]
