# Generated by Django 5.2 on 2025-04-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_member_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='تصویر پروفایل'),
        ),
    ]
