# Generated by Django 5.2 on 2025-04-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_member_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='test',
            field=models.TextField(null=True),
        ),
    ]
