# Generated by Django 5.2 on 2025-04-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_member_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='test',
        ),
    ]
