# Generated by Django 5.1.4 on 2024-12-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoollibrary', '0002_author_alter_book_author_rename_user_member_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='birth_date',
        ),
    ]
