# Generated by Django 5.1.4 on 2024-12-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoollibrary', '0006_alter_book_author_alter_book_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='placed_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='no-image-available-icon-vector.jpg', upload_to=''),
        ),
    ]
