# Generated by Django 5.1.4 on 2024-12-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoollibrary', '0007_book_placed_at_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='no-image-available-icon-vector.jpg', upload_to=''),
        ),
    ]
