# Generated by Django 5.1.4 on 2025-01-10 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, default='no-image-available-icon-vector.jpg', upload_to='')),
                ('slug', models.SlugField(default='-', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, unique=True)),
                ('membership_id', models.IntegerField(primary_key=True, serialize=False)),
                ('membership_start_date', models.DateField(auto_now_add=True)),
                ('membership_end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='no-image-available-icon-vector.jpg', upload_to='')),
                ('placed_at', models.DateField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('slug', models.SlugField(default='-', unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school-library.author')),
                ('category', models.ManyToManyField(to='school-library.category')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_on', models.DateField(auto_now_add=True)),
                ('return_by', models.DateField()),
                ('status', models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='borrowed', max_length=32)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school-library.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school-library.member')),
            ],
        ),
    ]
