# Generated by Django 5.1.4 on 2025-01-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school-library', '0002_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
