# Generated by Django 5.1.4 on 2025-01-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school-library', '0004_remove_book_slug_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='slug',
        ),
    ]
